import joblib
import pandas as pd
import streamlit as st
from pathlib import Path

# ==========================================================
# Page Configuration
# ==========================================================

st.set_page_config(
    page_title="GenomeFlowAI",
    page_icon="🧬",
    layout="wide",
)

# ==========================================================
# Load Model
# ==========================================================

MODEL_PATH = Path("models/xgboost_model.joblib")

if not MODEL_PATH.exists():
    st.error("Model not found!")
    st.stop()

model = joblib.load(MODEL_PATH)

# ==========================================================
# Header
# ==========================================================

st.title("🧬 GenomeFlowAI")

st.markdown(
"""
### Cancer Clone Aggressiveness Prediction

Enter clone statistics generated by the simulator and let the
trained XGBoost model predict whether the clone is aggressive.
"""
)

st.divider()

# ==========================================================
# Inputs
# ==========================================================

left, right = st.columns(2)

with left:

    generation = st.slider(
        "Generation",
        0,
        100,
        20
    )

    clone_size = st.number_input(
        "Clone Size",
        min_value=1,
        value=67000
    )

    clone_fraction = st.slider(
        "Clone Fraction",
        0.0,
        1.0,
        0.04,
        step=0.01
    )

    average_fitness = st.slider(
        "Average Fitness",
        0.0,
        10.0,
        1.60,
        step=0.05
    )

with right:

    average_age = st.slider(
        "Average Age",
        0,
        100,
        80
    )

    passenger_mutations = st.slider(
        "Passenger Mutations",
        0.0,
        20.0,
        3.8,
        step=0.1
    )

    driver_mutations = st.slider(
        "Driver Mutation Count",
        0,
        8,
        4
    )

st.divider()

# ==========================================================
# Prediction
# ==========================================================

if st.button(
    "Predict Aggressiveness",
    use_container_width=True
):

    sample = pd.DataFrame({
        "generation":[generation],
        "clone_size":[clone_size],
        "clone_fraction":[clone_fraction],
        "average_fitness":[average_fitness],
        "average_age":[average_age],
        "average_passenger_mutations":[passenger_mutations],
        "driver_mutation_count":[driver_mutations],
    })

    prediction = model.predict(sample)[0]

    probability = model.predict_proba(sample)[0]

    confidence = probability.max()*100

    risk = probability[1]*100

    st.divider()

    c1,c2,c3 = st.columns(3)

    with c1:

        if prediction==1:
            st.error("### 🔴 Aggressive")
        else:
            st.success("### 🟢 Non-Aggressive")

    with c2:

        st.metric(
            "Confidence",
            f"{confidence:.2f}%"
        )

    with c3:

        st.metric(
            "Risk Score",
            f"{risk:.1f}/100"
        )

    st.subheader("Prediction Probability")

    st.write("Aggressive")

    st.progress(float(probability[1]))

    st.write(
        f"{probability[1]*100:.2f}%"
    )

    st.write("Non-Aggressive")

    st.progress(float(probability[0]))

    st.write(
        f"{probability[0]*100:.2f}%"
    )

    st.divider()

    st.subheader("Input Summary")

    st.dataframe(
        sample,
        use_container_width=True
    )

    st.divider()

    st.subheader("Model Interpretation")

    if prediction==1:

        st.warning(
"""
The model predicts that this clone is **likely to become aggressive**.

This prediction is influenced by the overall fitness, mutation burden,
clone size and evolutionary characteristics learned during training.
"""
        )

    else:

        st.info(
"""
The model predicts that this clone is **currently non-aggressive**.

Based on the learned patterns, the clone exhibits characteristics
associated with slower tumour progression.
"""
        )

# ==========================================================
# Reports
# ==========================================================

st.divider()

st.header("Training Reports")

tab1,tab2,tab3,tab4 = st.tabs([
    "Feature Importance",
    "SHAP",
    "ROC Curve",
    "Confusion Matrix"
])

with tab1:

    path="reports/feature_importance.png"

    if Path(path).exists():
        st.image(path,use_container_width=True)

with tab2:

    path="reports/shap_summary.png"

    if Path(path).exists():
        st.image(path,use_container_width=True)

with tab3:

    path="reports/roc_curve.png"

    if Path(path).exists():
        st.image(path,use_container_width=True)

with tab4:

    path="reports/confusion_matrix.png"

    if Path(path).exists():
        st.image(path,use_container_width=True)

st.divider()

st.caption(
    "GenomeFlowAI • High-Performance Cancer Evolution Simulation & Explainable AI"
)